### ISSUE TITLE
Understanding patterns

### ISSUE THREAD

**Issue by saswat0** [EIDOSlab/entangling-disentangling-bias#6]
@carloalbertobarbano @enzotarta 

Kudos on this great work!

I had a trivial question. In the paper, you mention that disentanglement happens for the bias-guiding patterns, and entanglement happens for the bias-conflicting patterns. Well, how do you figure out the nature of these "patterns" from the feature dim?

**Comment by carloalbertobarbano** [comment]
Hello and thanks for the interest. If I understand your question, we are assuming that we have a prior knowledge (i.e. label) about the bias "class" for each sample; that way we can distinguish bias-aligned and bias-conflicting samples.

**Comment by saswat0** [comment]
Thanks for the response. 
How do you find the exact features (from the latent feature block) which belong to a target or bias attribute?

**Comment by carloalbertobarbano** [comment]
I see your question now. This is done automatically by the optimization process, because you are minimizing jointly the loss (on the target label) and the regularization term (on the bias label). So, when the terms are both minimized, the latent space will contain the target features and it will be (hopefully) invariant to the bias features. 

If you are wondering how the bias information in the latent space maps to the input image (visual interpretation of the bias) that is a very good question, and it is not easy to answer. We tried showing with grad cam that a biased model focuses on wrong parts of the image, but of course grad cam is not always reliable. 

I hope this answers your question

**Comment by saswat0** [comment]
Ahh I see. Got it. Thanks for such a lucid explanation
